version: "3"
services:
    cms-main-db:
      image: postgres
      container_name: cms_main_db
      restart: always
      volumes:
        - ./data/main/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=cms_main_server
        - POSTGRES_USER=main
        - POSTGRES_PASSWORD=20121208
      ports:
        - "5432:5432"

    cms-main:
        image: snslabdocker/cms_main
        container_name: cms_main
        depends_on:
          - cms-main-db
        restart: always
        command: sh -c "/bin/bash /root/LivingLab-CCS/Livinglab_CMS/Livinglab/Livinglab-CMS/cms_main_server/start_cms.sh"
        #command: /bin/bash -c "while true; do echo test; sleep 100; done"
        ports:
          - "8000:8000"
        environment:
          - HOST_IP=203.250.32.193
          - DATABASE_IP=cms-main-db

    cms-shelter-db:
      image: postgres
      container_name: cms_shelter_db
      restart: always
      command: -p 5433
      volumes:
        - ./data/shelter/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=cms_shelter_server
        - POSTGRES_USER=shelter
        - POSTGRES_PASSWORD=20121208
      ports:
        - "5433:5433"

    cms-shelter:
        image: snslabdocker/cms_shelter
        container_name: cms_shelter
        depends_on:
          - cms-shelter-db
        restart: always
        command: sh -c "/bin/bash /root/LivingLab-ShelterServer/local_shelter_server/start_shelter.sh"
        #command: /bin/bash -c "while true; do echo test; sleep 100; done"
        ports:
          - "8001:8000"
          - "5000:5000"
        environment:
          - CMS_MAIN_IP=203.250.32.193
          - DATABASE_IP=cms-shelter-db